version: '3.8'

services:
  sims_ppob_service:
    build: .
    working_dir: /app
    container_name: sims_ppob_service
    depends_on:
      - sims_ppob_db
    ports:
      - "80:80"
    networks:
      - sims_ppob_network
    restart: always
    # volumes:
    #   - .:/app

  sims_ppob_db:
    image: mysql:8.0
    container_name: sims_ppob_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sims_ppob_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - sims_ppob_network
    volumes:
      - sims_ppob_db_data:/var/lib/mysql

networks:
  sims_ppob_network:
    driver: bridge

volumes:
  sims_ppob_db_data: